#!/usr/bin/env python3

# switch `ailia-task` alias to: /opt/ailia-models/{task_id}/{model_id}/{model_id}.py
# Usage example: ailia-task --input folder1 --savepath folder1/folder2/model_folder -m model1

import os
import sys
import subprocess

def get_argument(ar):
    try:
        if ar in sys.argv:
            task_index = sys.argv.index(ar) + 1
            if task_index < len(sys.argv):
                return sys.argv[task_index]
        return None
    except ValueError:
        return None

models_abspath = os.getenv('AILIA_MODELS_PATH', default = '/opt/ailia-models')

task_id = get_argument('--task')
if not task_id:
    task_id = os.getenv('AILIA_TASK_ID', default = 'background_removal')

model_id = sys.argv[sys.argv.index('-m') + 1]
input_path = sys.argv[sys.argv.index('--input') + 1]
output_path = sys.argv[sys.argv.index('--savepath') + 1]

cmd = 'PYTHONPATH={models_abspath}/util python3 {models_abspath}/{task_id}/{model_id}/{model_id}.py --input {input_path} --savepath {output_path}'.format(
    input_path = input_path,
    output_path = output_path,
    models_abspath = models_abspath,
    task_id = task_id,
    model_id = model_id
)

print(cmd)
subprocess.run(cmd, shell=True)
